import os
import json
import urllib.request
import urllib.parse
import urllib.error
from dotenv import load_dotenv

def test_storage():
    backend_dir = os.path.dirname(os.path.abspath(__file__))
    dotenv_path = os.path.join(backend_dir, '.env')
    load_dotenv(dotenv_path)

    api_key = os.getenv("GOOGLE_API_KEY") or os.getenv("NEXT_PUBLIC_FIREBASE_API_KEY")
    bucket_name = os.getenv("NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET") or "mlsc-30.firebasestorage.app"

    print(f"Testing Storage REST API for Bucket: {bucket_name}")
    
    # 1. Create a dummy text file
    dummy_text = "Hello Firebase Storage REST API!"
    local_test_file = os.path.join(backend_dir, "test_rest.txt")
    with open(local_test_file, "w") as f:
        f.write(dummy_text)
        
    storage_path = "test/test_rest.txt"
    
    # URL encode path
    encoded_path = urllib.parse.quote(storage_path, safe='')
    upload_url = f"https://firebasestorage.googleapis.com/v0/b/{bucket_name}/o?uploadType=media&name={encoded_path}&key={api_key}"
    
    print(f"Uploading file to: {upload_url}")
    
    try:
        with open(local_test_file, "rb") as f:
            file_data = f.read()
            
        req = urllib.request.Request(
            upload_url,
            data=file_data,
            headers={"Content-Type": "text/plain"}
        )
        
        with urllib.request.urlopen(req) as response:
            res_body = response.read().decode('utf-8')
            print("Storage REST Upload SUCCESS!")
            print(res_body)
            metadata = json.loads(res_body)
            # The download token is generated by Firebase
            download_tokens = metadata.get("downloadTokens", "")
            print(f"Download token: {download_tokens}")
            
    except Exception as e:
        print(f"Storage REST Upload FAILED: {e}")
        if hasattr(e, "read"):
            print(e.read().decode('utf-8'))
            
    # 2. Download file back
    download_url = f"https://firebasestorage.googleapis.com/v0/b/{bucket_name}/o/{encoded_path}?alt=media&key={api_key}"
    print(f"Downloading from: {download_url}")
    
    try:
        req = urllib.request.Request(download_url)
        with urllib.request.urlopen(req) as response:
            content = response.read().decode('utf-8')
            print("Storage REST Download SUCCESS!")
            print(f"Content: '{content}'")
            assert content == dummy_text, "Content mismatch!"
            print("Integrity check passed!")
    except Exception as e:
        print(f"Storage REST Download FAILED: {e}")
        
    # Clean up local file
    if os.path.exists(local_test_file):
        os.remove(local_test_file)

if __name__ == "__main__":
    test_storage()
